name: Lint Markdown

# This action will trigger on every push to any branch.
on: [push]

jobs:
  # This is the name of the job. You can name it anything.
  markdown-lint:
    # This is the type of machine to run the job on. 'ubuntu-latest' is a good default.
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your code from the repository.
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Run the linter. This is the actual scanner.
      - name: Run Markdown Lint
        uses: davidanson/markdownlint-cli2-action@v16
